spring:
  profiles:
    active: dev

---
#---------------------------------------------------
#            GLOBAL CONFIGURATION
#---------------------------------------------------

info:
  name: Home Work Organizer
app:
  description: ${info.name} est une application pour l'ESGI
spring:
  application:
    name:  H.W.O APPLICATION
application:
  version: 1.0
server:
  port: 8080

logging:
  level:
    com:
      ileossa:
        controller:
          PlaylistController: WARM
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
  file: LOGS/${info.name}${random.value}.log

multipart:
  max-file-size: 10Mb
  max-request-size: 10Mb



---
#---------------------------------------------------
#            DEVELOPER  MODE
#---------------------------------------------------
spring:
  profiles: dev
  jpa:
    show-sql: true
  jmx:
    enabled: true
  h2:
    console:
      enabled: true
# url pour accéder à la console H2, est la suivante par défaut : http://localhost:8080/h2-console/
# en cas de changement voir dans les logs au démarage une route ("/h2-console") affiché
---
#---------------------------------------------------
#            TEST  MODE
#---------------------------------------------------
spring:
  profiles: test
  jpa:
    show-sql: true
  jmx:
    enabled: true
server:
  port: 8080

---
#---------------------------------------------------
#            PRODUCTION  MODE
#---------------------------------------------------

#configuration de la base de donnée postgresSql lors du basculement du service sur les server Heroku, pour tout autre hébergeur ce reporter à la documentation ou à l'url suivante
#           http://docs.spring.io/spring-boot/docs/current/reference/html/cloud-deployment.html
spring:
  profiles: prod
  datasource:
    url: ${JDBC_DATABASE_URL}
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    min-idle: 2
    initialSize: 5
    removeAbandoned: true
  jpa:
    show-sql: false
  jmx:
    enabled: false
